### ISSUE TITLE
Add support for OpenCart 4.0.2.x & PHP 8.3

### ISSUE THREAD

**Issue by jorimvanhove** [MultiSafepay/opencart-4#1]
Starting from OpenCart v4.0.2.x, the `GetMethod` function in payment modules is renamed to `GetMethods`. This is a breaking change and results in an notice while fetching the built-in payment methods, which terminates execution of the event method.

Notice: Undefined property: Proxy::getMethod in /htdocs/extension/multisafepay/system/library/multisafepayevents.php on line 102

The result is that no MultiSafePay payment methods are displayed in the checkout.

See https://github.com/opencart/opencart/blame/fa8ecb37df3ce9894f75465a5b40ff41b48b8f5f/upload/extension/opencart/catalog/model/payment/cod.php#L4

Affected plugin version: 1.3.0

**Comment by danielcivit** [comment]
Hi @jorimvanhove .

Thanks for your comment and for contacting us. 

We are fully aware of this issue and fully understand your feedback.  At this moment, this module only supports versions 4.0.1.1 or lower and for such versions, should work as expected. 

We have an item in the backlog to support 4.0.2.x but it`s not clear when this will be released. 

If you are or represent a MultiSafepay merchant, please contact your business account manager, in that way, your business case will be considered and priorities could change. 
 
We will keep this ticket open, to get back to you once a new version supporting OpenCart 4.0.2.x is released

**Comment by danielcivit** [comment]
Hi @jorimvanhove 

Once again, thanks for your comment and for contacting us.

We just released a new version, that supports OpenCart 4.0.2.0 up to 4.0.2.3

Support for OpenCart 4.0.0.0 until 4.0.1.1 has been dropped. Unfortunately, as you probably know, those versions are not stable and are full of bugs, and the changes introduced since 4.0.2.x can be considered breaking changes.

I am closing this ticket now, but feel welcome to contact us if you needed.
